spring.application.name=QuickCab
spring.datasource.url=jdbc:mysql://localhost:3306/quickcab_db
spring.datasource.username=root
spring.datasource.password=prasanth007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
